// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/driver-demo-layouts/Cockpit.tsx": () => import("../components/mockups/driver-demo-layouts/Cockpit.tsx"),
  "./components/mockups/driver-demo-layouts/IncidentBoard.tsx": () => import("../components/mockups/driver-demo-layouts/IncidentBoard.tsx"),
  "./components/mockups/driver-demo-layouts/ScoreFirst.tsx": () => import("../components/mockups/driver-demo-layouts/ScoreFirst.tsx")
};
